// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlc-O_SXa9QB1pxuT_dsCiP4rNKYyMkA',
    appId: '1:258810302381:web:7c70d9eb53570402481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    authDomain: 'nossosmomentos-22.firebaseapp.com',
    databaseURL: 'https://nossosmomentos-22-default-rtdb.firebaseio.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
    measurementId: 'G-BYNL78VXWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtcdjW51vhA3ht_8JnENemT6-gCnmCmU',
    appId: '1:258810302381:android:80bce144dd1e6ff7481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    databaseURL: 'https://nossosmomentos-22-default-rtdb.firebaseio.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuVAm7Bo061JGPe9FoYfGJRIbJYu8PME',
    appId: '1:258810302381:ios:2285e0e041d5c09e481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    databaseURL: 'https://nossosmomentos-22-default-rtdb.firebaseio.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
    iosBundleId: 'br.com.lovestudios.nossosmomentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEuVAm7Bo061JGPe9FoYfGJRIbJYu8PME',
    appId: '1:258810302381:ios:d5218bbb0dab6e3c481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    databaseURL: 'https://nossosmomentos-22-default-rtdb.firebaseio.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
    iosBundleId: 'br.com.lovestudios.nossosmomentos.nossosMomentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNfvYG6gD1IrdNnQw2O3YqKnkVLxn1dqU',
    appId: '1:258810302381:web:2201554c7357ada3481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    authDomain: 'nossosmomentos-22.firebaseapp.com',
    databaseURL: 'https://nossosmomentos-22-default-rtdb.firebaseio.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
    measurementId: 'G-1LZQMXZ5LD',
  );

}