// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlc-O_SXa9QB1pxuT_dsCiP4rNKYyMkA',
    appId: '1:258810302381:web:7c70d9eb53570402481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    authDomain: 'nossosmomentos-22.firebaseapp.com',
    storageBucket: 'nossosmomentos-22.appspot.com',
    measurementId: 'G-BYNL78VXWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtcdjW51vhA3ht_8JnENemT6-gCnmCmU',
    appId: '1:258810302381:android:80bce144dd1e6ff7481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    storageBucket: 'nossosmomentos-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuVAm7Bo061JGPe9FoYfGJRIbJYu8PME',
    appId: '1:258810302381:ios:d5218bbb0dab6e3c481b24',
    messagingSenderId: '258810302381',
    projectId: 'nossosmomentos-22',
    storageBucket: 'nossosmomentos-22.appspot.com',
    iosClientId: '258810302381-vlpq2or1f9kr45bvjp5fp4f33rtu4745.apps.googleusercontent.com',
    iosBundleId: 'br.com.lovestudios.nossosmomentos.nossosMomentos',
  );
}
